# Generated by Django 5.1.2 on 2024-10-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('area', models.CharField(choices=[('recursos_humanos', 'Recursos Humanos'), ('finanzas', 'Finanzas'), ('marketing', 'Marketing '), ('ventas', 'Ventas'), ('atencion_al_cliente', 'Atencion al Cliente')], max_length=50)),
                ('servicio', models.CharField(choices=[('impresora', 'Impresion'), ('software', 'Software'), ('servidor', 'Servidor'), ('hardware', 'Hardware')], max_length=50)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=50)),
                ('encargado', models.CharField(choices=[('maniquil', 'Maria Aniquil'), ('gsoto', 'Guido Soto'), ('jmunoz', 'Jorge Munoz')], max_length=50)),
                ('descripcion_del_problema', models.TextField()),
            ],
        ),
    ]
