# Generated by Django 5.1.2 on 2024-11-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='descripcion_del_problema',
        ),
        migrations.AddField(
            model_name='ticket',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('en_proceso', 'En Proceso')], default='abierto', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='retroalimentacion_soporte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='satisfaccion_cliente',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('----', '----')], default='----', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='area',
            field=models.CharField(choices=[('finanzas', 'Finanzas'), ('marketing', 'Marketing'), ('ventas', 'Ventas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='servicio',
            field=models.CharField(choices=[('impresora', 'Impresión'), ('software', 'Software'), ('servidor', 'Servidor'), ('hardware', 'Hardware')], max_length=50),
        ),
    ]
