# Generated by Django 5.1.2 on 2024-11-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_remove_ticket_descripcion_del_problema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('en_proceso', 'En Proceso')], default='---------', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='satisfaccion_cliente',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('----', '----')], default='---------', max_length=10),
        ),
    ]
